// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9fEUOwFTWSyhSqBlzCkUUeFtpIEFscd4',
    appId: '1:849052348139:ios:f461506c43932687b718ae',
    messagingSenderId: '849052348139',
    projectId: 'bibliotheque-2d507',
    storageBucket: 'bibliotheque-2d507.firebasestorage.app',
    iosBundleId: 'fr.limoges.valadon.bibliotheque.bibliotheque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9fEUOwFTWSyhSqBlzCkUUeFtpIEFscd4',
    appId: '1:849052348139:ios:f461506c43932687b718ae',
    messagingSenderId: '849052348139',
    projectId: 'bibliotheque-2d507',
    storageBucket: 'bibliotheque-2d507.firebasestorage.app',
    iosBundleId: 'fr.limoges.valadon.bibliotheque.bibliotheque',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpAjsPNbNAR4c8k0_Pe_8tHAnWI5ucoZs',
    appId: '1:849052348139:web:358934248c2d11c9b718ae',
    messagingSenderId: '849052348139',
    projectId: 'bibliotheque-2d507',
    authDomain: 'bibliotheque-2d507.firebaseapp.com',
    storageBucket: 'bibliotheque-2d507.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDee3wiNJBPBdpSwwme2xuj-hXMUyn10ug',
    appId: '1:849052348139:android:d8f51fa26ef9761ab718ae',
    messagingSenderId: '849052348139',
    projectId: 'bibliotheque-2d507',
    storageBucket: 'bibliotheque-2d507.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpAjsPNbNAR4c8k0_Pe_8tHAnWI5ucoZs',
    appId: '1:849052348139:web:ad2f6e96f64c8421b718ae',
    messagingSenderId: '849052348139',
    projectId: 'bibliotheque-2d507',
    authDomain: 'bibliotheque-2d507.firebaseapp.com',
    storageBucket: 'bibliotheque-2d507.firebasestorage.app',
  );

}